### PR TITLE
Update mitchell-busschers.md

### PR DESCRIPTION
**Pull request by eaulav**
for fucking up on the git pull-request by @frankyxl

### CODE REVIEW

**Comment by hipio** [comment]
👎

**Comment by frenck** [comment]
:+1

**Comment by Potherca** [comment]
I am not sure I entirely agree with this one.

**Comment by frenck** [comment]
he correct it... We don't give you one every single time you hit the wrong button?

**Comment by eaulav** [comment]
meh...

**Comment by Marascon** [comment]
:-1: no.

**Pull request closed without merging**
