### PR TITLE
Awards crown to Frank

### PR DESCRIPTION
**Pull request by Potherca**
For making the awesome burn-down race track!

### CODE REVIEW

**Comment by hipio** [comment]
Burn-down race track?

**Comment by Potherca** [comment]
On the white board. Part of the scrum effort is usually a [burn down chart](https://en.wikipedia.org/wiki/Burn_down_chart). We felt that a racetrack would be more fitting for us (as a company).

**Comment by hipio** [comment]
Ah, I see. Burn down charts are usually quite boring, yes.

**Comment by hipio** [comment]
🚢

**Pull request merged**
