### PR TITLE
Adds Knut to members file.

### PR DESCRIPTION
**Pull request by Potherca**
So we can give him some nice badges!

### CODE REVIEW

**Comment by Marascon** [comment]
Cant approve this  "Data Science" : {
should be 
 "name": "Data Science",

**Comment by Marascon** [comment]
:facepunch:

**Comment by Potherca** [comment]
I had also used `member` instead of `members`. :crying_cat_face:

Fixed now.

**Comment by eaulav** [comment]
👍

**Comment by frenck** [comment]
Looking fine now! 🚢

**Pull request merged**
