### PR TITLE
Give Mitchell a Patrick

### PR DESCRIPTION
**Pull request by hipio**
A Patrick for switching Knut with Ben and vice-versa.

### CODE REVIEW

**Comment by Marascon** [comment]
:astonished: Giving himself badges

**Comment by Potherca** [comment]
I can support the Patrick but I am not too sure about the pencil as #107 already takes care of that... Unless you can add more details (in person) about which other docs you are referring to.

Or maybe even give a little demo? 😁

**Comment by hipio** [comment]
Oh, I forgot about that one, haha. Uuuh, only do the Patrick then. ;)

2016-09-14 21:32 GMT+02:00 Ben Peachey <notifications@github.com>:

**Comment by Potherca** [comment]
FTFY

**Pull request merged**
