### PR TITLE
Fixing wrong badge assigned by Mr. PaasEi.

### PR DESCRIPTION
**Pull request by Potherca**
@pimkaptein You might want to approve this a.s.a.p.

### CODE REVIEW

**Comment by pimkaptein** [comment]
Already corrected and i awarded a medal. You want to award a thumb or want to do my work.... @Potherca

**Comment by eaulav** [comment]
🚢

**Comment by eaulav** [comment]
OWWWWWWWW BOOM

**Comment by Potherca** [comment]
:bomb: :boom:

**Pull request merged**
