### PR TITLE
Upload Pie Badge

### PR DESCRIPTION
**Pull request by frankyxl**
Uploaded the pie badge to svg folder. (Pie badge for people who bring a pie ((while not celebrating a birthday))

### CODE REVIEW

**Comment by Potherca** [comment]
Y U NO PNG?

**Comment by eaulav** [comment]
👍

**Comment by eaulav** [comment]
@Potherca png is so 2015

**Comment by frankyxl** [comment]
SVG ole ole ole

**Comment by Potherca** [comment]
Yeah, but without PNG we can't link images in environments that don't support SVG (like Attlassian, which is also _so_ 2015)

**Comment by hipio** [comment]
@Potherca: Then PNG's have to be made for the 5 badges that were introduced in PR #154 as well.

**Comment by Potherca** [comment]
@hipio Correct. The PNG directory is a mess as it is... The names don't match, there are badges there that are not present in the SVG folder, etc. :crying_cat_face:

**Comment by frankyxl** [comment]
I will fix it!

**Comment by frankyxl** [comment]
@#%^$%^$%^%^@! you guys gave custom names, now they don't match to my photoshop layerzzzzzzz! From now on when requesting a badge also provide the filename 💃  @Potherca

**Comment by Marascon** [comment]
:hamster:

**Pull request merged**
