### PR TITLE
Create Meike in Achievements

### PR DESCRIPTION
**Pull request by pimkaptein**

### CODE REVIEW

**Comment by Marascon** [comment]
This wont fly..

The first step is to add an employee by editing the _data/members.json file.

**Comment by pimkaptein** [comment]
I did not know that! Will do this!

**Comment by Marascon** [comment]
its in the README FOOL!

**Comment by eaulav** [comment]
see readme for adding a new user

**Comment by Marascon** [comment]
:+1: 

Next time there is a a README.MD :laughing:

**Pull request merged**
